spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml



  servlet:
    session:
      timeout: 600

